### ISSUE TITLE
Can't we use /dev/stdin or named pipes?

### ISSUE THREAD

**Issue by purpleP** [dojoteef/neomake-autolint#1]
/dev/stdin instead of temp files? Because if you use tempfiles than this is no better than just save file on every exit from insert mode.

**Comment by dojoteef** [comment]
I chose the approach such that it has no external requirements and would work with any linter. I mentioned my reasoning [here](https://github.com/neomake/neomake/issues/543#issuecomment-250242341):

> I appreciate the idea of piping the file, but it is limited in scope as many linters do not support reading from stdin. Using a pipe as the only way to accomplish linting the unwritten buffer seems to help only some workflows rather than something that would work for everyone.

and [here](https://github.com/neomake/neomake/issues/543#issuecomment-250284320)

> Though I have not surveyed all the linters, I would venture to say most linters do not support reading from stdin. For example it wouldn't work for common usecases that anyone writing shell scripts or vim plugins might use like [shellcheck](http://www.shellcheck.net/) and [vint](https://github.com/Kuniwak/vint). In fact if using [programming language popularity](http://pypl.github.io/PYPL.html), Java is # 1 with nearly 25% of the share of search popularity, and neither of the two supported neomake linters javac -xlint nor [checkstyle](http://checkstyle.sourceforge.net/) support reading from stdin.

The same reasoning holds true for using pipes or other such constructs. That said, this approach is much different than simply saving the file every time you exit insert mode.

**Comment by purpleP** [comment]
@dojoteef And as I've said there can't you use /dev/stdin or named pipe?

**Comment by dojoteef** [comment]
Interestingly [ALE](https://github.com/w0rp/ale) tries to use your stdin approach. Though in their [docs](https://github.com/w0rp/ale/blob/f9cbc69ce1368ffde415a51bd59a1b271d269748/doc/ale.txt) they mention this (emphasis added):

>  Some programs for checking for errors are not capable of receiving input
>   from stdin, as is required by ALE. To remedy this, a wrapper script is
>   provided named in the variable |g:ale#util#stdin_wrapper|. This variable
>   can be called with the regular arguments for any command to forward data
>   from stdin to the program, by way of **creating a temporary file**.

For maintainability I do not believe in maintaining two different approaches especially when one falls back to the approach implemented in this plugin. If that is a feature you desire maybe [ALE](https://github.com/w0rp/ale) would work better for you.

**Comment by purpleP** [comment]
@dojoteef How is creating a temporary file is "using my approach"? It's exactly the opposite. Creating a real temporary file is inefficient and quite stupid, when you can do this.
`cat file_to_lint | linter-that-dont-support-stdin /dev/stdin`
or named pipe
`mkfifo /tmp/file_to_lint && cat file_to_lint > /tmp/file_to_lint && linter-that-dont-support-stdin /tmp/file_to_lint`

You see, if you creating temporary files than you doing no better than just saving the buffer on each change and executing neomake in BufWrite autocmd. Maybe I don't understand something here? I would do that, but I don't know much about vimscript right now. I've tried to look at the code of ALE and Neomake, but after 10-15 minutes I just gaved up.

**Comment by dojoteef** [comment]
@purpleP Please try to keep this civil. No need to refer to approaches as stupid.

That said please re-read my comment carefully. I never stated a temporary file was your approach, rather that using stdin was and that [ALE](https://github.com/w0rp/ale) uses stdin by default for linters that support stdin. Since not all linters support reading from stdin they decided to use a temporary file in those cases.

Unfortunately `mkfifo` is not available by default on all major systems that [Vim](http://vim.org) supports (Window for example). Considering it is likely a trivial amount of work, I will look into using a named pipe on systems that have `mkfifo`.

As for learning vimscript I did not know it well either, nor did I know the [Neomake](https://github.com/neomake/neomake) code. Rather I spent the time to learn it because I felt linting on the fly was important to me. If you find that you cannot get the features you desire in a plugin I suggest you be part of the solution. Take the initiative even though it may take more than 10-15 minutes of your time. This has definitely taken more of my time than that.

**Comment by purpleP** [comment]
@dojoteef Sorry, I just a bit disappointed because I keep telling it everywhere, yet no one (except you) listens.
The problem with doing it myself isn't that it could take more then 15 minutes, but that it can take a lot more, because after reading neomake code for 15 minutes, I haven't understand it a bit. I've skimmed over ALE code and I think it more clean, so maybe I could somehow change what they're doing with temporary files, but I'm not sure about that.

**Comment by dojoteef** [comment]
@purpleP I just took a quick look and I feel that using a named pipe is more maintenance overhead than it is worth. The reason is not all linters seem to support named pipes, go figure. For example I just tried [vint](https://github.com/Kuniwak/vint), which is used to lint vimscript, with a named pipe and it failed. Looking at the [code](https://github.com/Kuniwak/vint/blob/cc0499a/vint/linting/cli.py#L48-L50) it apparently uses [pathlib](https://docs.python.org/3/library/pathlib.html)'s is_file which fails since a named pipe is not an ordinary file:

```
terminal1> mkfifo -m 600 tmpfile && cat .vimrc > tmpfile
terminal2> vint --style-problem --no-color tmpfile
vint ERROR: no such file or directory: `/Users/nsa/tmpfile`
```

Considering that this approach does not work for some linters means more maintenance to determine which linters can use a named pipe and which cannot, which could require changes to this plugin when [Neomake](https://github.com/neomake/neomake) adds a new linter, while the current approach would not.

Generally speaking the files that will be linted are so small that the slight overhead of writing a file to disk does not seem to be much of a concern, and could theoretically be mitigated by using a [RAM disk](https://en.wikipedia.org/wiki/RAM_drive) or [tmpfs](https://en.wikipedia.org/wiki/Tmpfs) combined with the `g:neomake_autolint_cachedir` pointing to the appropriate place. By default many linux systems use [tmpfs](https://en.wikipedia.org/wiki/Tmpfs) for the `/tmp` directory, so nothing would be written to disk in that case.

What exactly is your reasoning to avoid writing to a temporary file?

**Comment by purpleP** [comment]
@dojoteef Yeah, I've just tried that on ghc and it also complaining.

**Comment by purpleP** [comment]
@dojoteef My main concern is ssd health.

**Comment by dojoteef** [comment]
@purpleP If SSD health is your main concern then either [tmpfs](https://en.wikipedia.org/wiki/Tmpfs) or a [RAM disk](https://en.wikipedia.org/wiki/RAM_drive) could address your concerns while using this plugin as I mentioned above.

We have both verified that neither stdin nor named pipes work for all linters which is a requirement if I were to implement one of those approaches. If you use specific linters that allow reading from stdin then [ALE](https://github.com/w0rp/ale) might be a better fit for you.

I am going to close this out this issue out for now. Cheers!

**Comment by bounceme** [comment]
Vim makes a lot of temps already : `h shelltemp`

**Comment by bounceme** [comment]
Actually, all `system()` calls (which are very popular, and how syntastic and non-async neomake work) use tmpfiles, except for neovim which changed to using pipes for `system()`
