### ISSUE TITLE
Linters pollute into other buffers

### ISSUE THREAD

**Issue by junkblocker** [dojoteef/neomake-autolint#17]
Often when a linter was run in one buffer on some filetype, it also get stuck to different buffers with entirely different filetype. For example, I edit a markdown file and markdown_mdl_autolint messages are seen. I switch to a golang file and markdown_mdl_autolint type starts running on that buffer too. Seems ``neomake#autolint#buffer#makers(bufnr) abort`` has race conditions or other environment corruption going on.

**Comment by blueyed** [comment]
This might also be caused by Neomake itself - I've seen issues related to this.
The logfile (via `let g:neomake_logfile = '/tmp/neomake.log`) would help here.

FYI: there is some WIP to have autolinting in Neomake itself (https://github.com/neomake/neomake/pull/1055), with milestones like handling modified buffers (https://github.com/neomake/neomake/pull/1057) and better restart/abort behavior (https://github.com/neomake/neomake/pull/1092).

**Comment by junkblocker** [comment]
Here's the log.

https://gist.github.com/junkblocker/d288840e7d6fa1a4ccb43424b8f46108

Reproduced the issue by 

1) opening a ``README.md`` and a ``main.go``
2) Type something into ``README.md`` and quickly switch to ``main.go`` which neomake/autolint is still working. ``main.go`` now starts getting treated as markdown showing ``markdown_mdl_autolint`` lint issues.

It took a few but not too many attempts so there is some log noise towards the beginning.

**Comment by blueyed** [comment]
Neomake supports automaking by now itself.. :fireworks: 
Hopefully without this issue - otherwise please let me know over in Neomake's issue tracker.

**Comment by dojoteef** [comment]
The README now clearly states the plugin is deprecated (I haven't actually had the time to update it for a while now anyway, sorry). If you are having any issues please try Neomake's builtin automake functionality.
