### ISSUE TITLE
sane autolinting when fixing errors

### ISSUE THREAD

**Issue by DerWeh** [dojoteef/neomake-autolint#19]
I know that is a rather vague request, but is it possible for `neomake-autolint` to behave in  more 'sane' way when correcting errors?

Currently when I fix an error, `neomake-autlint` kicks in (like it should be), however it clears all my errors in the location list, so I have to wait for the linters to finish to fix the next one. 
I have something in mind like keeping the errors in every line but the edited until the linter finished running. (I know that is not very specific and I have no idea whether this is possible to reasonably implement.)

For this it would also be great to somehow remember the position, so that `:lnext` actually gives the next error and doesn't start over again. I don't know whether this plugin is the right place for this, or if it rather should be a separate one.

**Comment by blueyed** [comment]
(JFI: I am working towards having automaking/linting on the fly easily configurable in Neomake (https://github.com/neomake/neomake/pull/1167).  A lot of local changes are missing there though.)

I think Neomake is already better suited with regard to clearing the signs/highlights, and improving that for the list could be done as well: only when the first job finishes it would start to replace the list.

There will also be commands to temporarily disable/toggle autolinting; which sounds like something you could use by now already as a workaround?! - i.e. temporarily disable linting-on-the-fly.

> `:lnext` actually gives the next error

That's a bit harder - and really needs support in Neomake's core, since for this the location list needs better maintaining, and e.g. something like not replacing it altogether when a (automake) job starts.
(related: https://github.com/neomake/neomake/issues/1294)

**Comment by dojoteef** [comment]
The README now clearly states the plugin is deprecated (I haven't actually had the time to update it for a while now anyway, sorry). If you are having any issues please try Neomake's builtin automake functionality.
